spring.application.name=uftos
spring.devtools.livereload.enabled=true
spring.devtools.restart.enabled=true
spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}?stringtype=unspecified
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=de.uftos.config.CustomPostgreSQLDialect
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
spring.sql.init.schema-locations=classpath*:schema.sql
springdoc.writer-with-order-by-keys=true
springdoc.writer-with-default-pretty-printer=true

