/* Generated By:JavaCC: Do not edit this line. SyntaxCheckerTreeConstants.java Version 4.1d1 */
public interface SyntaxCheckerTreeConstants
{
  public int JJTDEFINITION = 0;
  public int JJTBOOL = 1;
  public int JJTBOOLVALUE = 2;
  public int JJTCODEBLOCK = 3;
  public int JJTCONTROLSEQUENCELIST = 4;
  public int JJTCONTROLSEQUENCE = 5;
  public int JJTCONTROLSEQUENCERETURN = 6;
  public int JJTRETURN = 7;
  public int JJTFOR = 8;
  public int JJTIF = 9;
  public int JJTFORALL = 10;
  public int JJTEXISTS = 11;
  public int JJTIMPLIES = 12;
  public int JJTOR = 13;
  public int JJTAND = 14;
  public int JJTNOT = 15;
  public int JJTISEMPTY = 16;
  public int JJTEQUALTION = 17;
  public int JJTELEMENTEQUALTION = 18;
  public int JJTNUMBEREQUALTION = 19;
  public int JJTELEMENT = 20;
  public int JJTELEMENTNAME = 21;
  public int JJTELEMENTATTRIBUTELIST = 22;
  public int JJTELEMENTATTRIBUTE = 23;
  public int JJTNUMBERELEMENT = 24;
  public int JJTNUMBERSET = 25;
  public int JJTNUMBERLIST = 26;
  public int JJTSET = 27;
  public int JJTSETNAME = 28;
  public int JJTATTRIBUTELIST = 29;
  public int JJTATTRIBUTE = 30;
  public int JJTVARIABLE = 31;
  public int JJTPARAMETERNAME = 32;
  public int JJTFILTER = 33;
  public int JJTFILTERLIST = 34;


  public String[] jjtNodeName = {
    "DEFINITION",
    "BOOL",
    "BOOLVALUE",
    "CODEBLOCK",
    "CONTROLSEQUENCELIST",
    "CONTROLSEQUENCE",
    "CONTROLSEQUENCERETURN",
    "RETURN",
    "FOR",
    "IF",
    "FORALL",
    "EXISTS",
    "IMPLIES",
    "OR",
    "AND",
    "NOT",
    "ISEMPTY",
    "EQUALTION",
    "ELEMENTEQUALTION",
    "NUMBEREQUALTION",
    "ELEMENT",
    "ELEMENTNAME",
    "ELEMENTATTRIBUTELIST",
    "ELEMENTATTRIBUTE",
    "NUMBERELEMENT",
    "NUMBERSET",
    "NUMBERLIST",
    "SET",
    "SETNAME",
    "ATTRIBUTELIST",
    "ATTRIBUTE",
    "VARIABLE",
    "PARAMETERNAME",
    "FILTER",
    "FILTERLIST",
  };
}
/* JavaCC - OriginalChecksum=323039ef0be297ee603109ddc256636e (do not edit this line) */
