package de.uftos.repositories.ucdl.parser.javacc;

@SuppressWarnings("checkstyle:all")
/* Generated By:JavaCC: Do not edit this line. SyntaxCheckerTreeConstants.java Version 4.1d1 */
public interface SyntaxCheckerTreeConstants {
  int JJTSTART = 0;
  int JJTDEFINITION = 1;
  int JJTBOOL = 2;
  int JJTBOOLVALUE = 3;
  int JJTCODEBLOCK = 4;
  int JJTCONTROLSEQUENCELIST = 5;
  int JJTCONTROLSEQUENCE = 6;
  int JJTRETURN = 7;
  int JJTFOR = 8;
  int JJTIF = 9;
  int JJTCONTROLSEQUENCERETURN = 10;
  int JJTFORALL = 11;
  int JJTEXISTS = 12;
  int JJTIMPLIES = 13;
  int JJTOPTIONALIMPLIES = 14;
  int JJTOR = 15;
  int JJTOPTIONALOR = 16;
  int JJTAND = 17;
  int JJTOPTIONALAND = 18;
  int JJTNOT = 19;
  int JJTISEMPTY = 20;
  int JJTELEMENTINSETOREQUATION = 21;
  int JJTELEMENTINSET = 22;
  int JJTEQUATION = 23;
  int JJTELEMENTEQUATION = 24;
  int JJTELEMENT = 25;
  int JJTELEMENTNAME = 26;
  int JJTELEMENTATTRIBUTELIST = 27;
  int JJTNUMBERELEMENT = 28;
  int JJTSET = 29;
  int JJTSETNAME = 30;
  int JJTSETMODIFICATION = 31;
  int JJTNUMBERSET = 32;
  int JJTNUMBERLIST = 33;
  int JJTATTRIBUTE = 34;
  int JJTVALUEREFERENCE = 35;
  int JJTFILTER = 36;
  int JJTFILTERLIST = 37;


  String[] jjtNodeName = {
      "START",
      "DEFINITION",
      "BOOL",
      "BOOLVALUE",
      "CODEBLOCK",
      "CONTROLSEQUENCELIST",
      "CONTROLSEQUENCE",
      "RETURN",
      "FOR",
      "IF",
      "CONTROLSEQUENCERETURN",
      "FORALL",
      "EXISTS",
      "IMPLIES",
      "OPTIONALIMPLIES",
      "OR",
      "OPTIONALOR",
      "AND",
      "OPTIONALAND",
      "NOT",
      "ISEMPTY",
      "ELEMENTINSETOREQUATION",
      "ELEMENTINSET",
      "EQUATION",
      "ELEMENTEQUATION",
      "ELEMENT",
      "ELEMENTNAME",
      "ELEMENTATTRIBUTELIST",
      "NUMBERELEMENT",
      "SET",
      "SETNAME",
      "SETMODIFICATION",
      "NUMBERSET",
      "NUMBERLIST",
      "ATTRIBUTE",
      "VALUEREFERENCE",
      "FILTER",
      "FILTERLIST",
  };
}
/* JavaCC - OriginalChecksum=edda98796ddc0b2ed6208768ff5d5ef1 (do not edit this line) */
