package de.uftos.repositories.ucdl.parser.javacc;

/* Generated By:JavaCC: Do not edit this line. SyntaxCheckerTreeConstants.java Version 4.1d1 */
public interface SyntaxCheckerTreeConstants
{
  public int JJTSTART = 0;
  public int JJTDEFINITION = 1;
  public int JJTBOOL = 2;
  public int JJTBOOLVALUE = 3;
  public int JJTCODEBLOCK = 4;
  public int JJTCONTROLSEQUENCELIST = 5;
  public int JJTCONTROLSEQUENCE = 6;
  public int JJTCONTROLSEQUENCERETURN = 7;
  public int JJTRETURN = 8;
  public int JJTFOR = 9;
  public int JJTIF = 10;
  public int JJTFORALL = 11;
  public int JJTEXISTS = 12;
  public int JJTIMPLIES = 13;
  public int JJTOR = 14;
  public int JJTAND = 15;
  public int JJTNOT = 16;
  public int JJTISEMPTY = 17;
  public int JJTEQUATION = 18;
  public int JJTELEMENTEQUATION = 19;
  public int JJTNUMBEREQUATION = 20;
  public int JJTELEMENT = 21;
  public int JJTELEMENTNAME = 22;
  public int JJTELEMENTATTRIBUTELIST = 23;
  public int JJTELEMENTATTRIBUTE = 24;
  public int JJTNUMBERELEMENT = 25;
  public int JJTNUMBERSET = 26;
  public int JJTNUMBERLIST = 27;
  public int JJTSET = 28;
  public int JJTSETNAME = 29;
  public int JJTATTRIBUTELIST = 30;
  public int JJTATTRIBUTE = 31;
  public int JJTVARIABLE = 32;
  public int JJTPARAMETERNAME = 33;
  public int JJTFILTER = 34;
  public int JJTFILTERLIST = 35;


  public String[] jjtNodeName = {
    "START",
    "DEFINITION",
    "BOOL",
    "BOOLVALUE",
    "CODEBLOCK",
    "CONTROLSEQUENCELIST",
    "CONTROLSEQUENCE",
    "CONTROLSEQUENCERETURN",
    "RETURN",
    "FOR",
    "IF",
    "FORALL",
    "EXISTS",
    "IMPLIES",
    "OR",
    "AND",
    "NOT",
    "ISEMPTY",
    "EQUATION",
    "ELEMENTEQUATION",
    "NUMBEREQUATION",
    "ELEMENT",
    "ELEMENTNAME",
    "ELEMENTATTRIBUTELIST",
    "ELEMENTATTRIBUTE",
    "NUMBERELEMENT",
    "NUMBERSET",
    "NUMBERLIST",
    "SET",
    "SETNAME",
    "ATTRIBUTELIST",
    "ATTRIBUTE",
    "VARIABLE",
    "PARAMETERNAME",
    "FILTER",
    "FILTERLIST",
  };
}
/* JavaCC - OriginalChecksum=42658a83fa248d5812b330ba17f9af61 (do not edit this line) */
