/* Generated By:JavaCC: Do not edit this line. SyntaxCheckerTreeConstants.java Version 4.1d1 */

package de.uftos.repositories.ucdl.parser.javacc;

@SuppressWarnings("all")


public interface SyntaxCheckerTreeConstants {
  int JJTSTART = 0;
  int JJTDEFINITION = 1;
  int JJTBOOLVALUE = 2;
  int JJTCODEBLOCK = 3;
  int JJTCONTROLSEQUENCE_LIST = 4;
  int JJTCONTROLSEQUENCE = 5;
  int JJTRETURN = 6;
  int JJTFOR = 7;
  int JJTIF = 8;
  int JJTCONTROLSEQUENCE_RETURN = 9;
  int JJTFOR_ALL = 10;
  int JJTEXISTS = 11;
  int JJTIMPLIES = 12;
  int JJTOPTIONAL_IMPLIES = 13;
  int JJTOR = 14;
  int JJTOPTIONAL_OR = 15;
  int JJTAND = 16;
  int JJTOPTIONAL_AND = 17;
  int JJTNOT = 18;
  int JJTIS_EMPTY = 19;
  int JJTBOOL = 20;
  int JJTELEMENT_IN_SET_OR_EQUATION = 21;
  int JJTELEMENT_IN_SET = 22;
  int JJTEQUATION = 23;
  int JJTELEMENT_EQUATION = 24;
  int JJTELEMENT = 25;
  int JJTELEMENT_NAME = 26;
  int JJTELEMENT_ATTRIBUTE_LIST = 27;
  int JJTNUMBERELEMENT = 28;
  int JJTSET = 29;
  int JJTSET_NAME = 30;
  int JJTSET_MODIFICATION = 31;
  int JJTNUMBER_SET = 32;
  int JJTNUMBER_LIST = 33;
  int JJTATTRIBUTE = 34;
  int JJTVALUE_REFERENCE = 35;
  int JJTFILTER = 36;
  int JJTFILTER_LIST = 37;


  String[] jjtNodeName = {
      "START",
      "DEFINITION",
      "BOOLVALUE",
      "CODEBLOCK",
      "CONTROLSEQUENCE_LIST",
      "CONTROLSEQUENCE",
      "RETURN",
      "FOR",
      "IF",
      "CONTROLSEQUENCE_RETURN",
      "FOR_ALL",
      "EXISTS",
      "IMPLIES",
      "OPTIONAL_IMPLIES",
      "OR",
      "OPTIONAL_OR",
      "AND",
      "OPTIONAL_AND",
      "NOT",
      "IS_EMPTY",
      "BOOL",
      "ELEMENT_IN_SET_OR_EQUATION",
      "ELEMENT_IN_SET",
      "EQUATION",
      "ELEMENT_EQUATION",
      "ELEMENT",
      "ELEMENT_NAME",
      "ELEMENT_ATTRIBUTE_LIST",
      "NUMBERELEMENT",
      "SET",
      "SET_NAME",
      "SET_MODIFICATION",
      "NUMBER_SET",
      "NUMBER_LIST",
      "ATTRIBUTE",
      "VALUE_REFERENCE",
      "FILTER",
      "FILTER_LIST",
  };
}
/* JavaCC - OriginalChecksum=626c849f4e12f749ebb66eaf7feec7b5 (do not edit this line) */
