name: Test
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  web-format-tests:
    name: Web Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./web

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: "./web/.nvmrc"

      - name: Run npm install
        run: npm ci

      - name: Run linter
        run: npm run lint
        if: ${{ !cancelled() }}

      - name: Run formatter
        run: npm run format
        if: ${{ !cancelled() }}

      - name: Run svelte checks
        run: npm run check:svelte
        if: ${{ !cancelled() }}

      - name: Run tsc
        run: npm run check:typescript
        if: ${{ !cancelled() }}

      # - name: Run unit tests & coverage
      #   run: npm run test:cov
      #   if: ${{ !cancelled() }}
